### ISSUE TITLE
mhamzas / Signature-using-LWC

### ISSUE THREAD

**Issue by yandrasindhu** [mhamzas/Signature-using-LWC#1]
Error creating Salesforce File record issue it is not saving...

**Comment by mhamzas** [comment]
Can you please share the screenshot or error message in debug_log

**Comment by yandrasindhu** [comment]
![image](https://user-images.githubusercontent.com/39753077/77984440-2b940700-732f-11ea-860a-62b0e2ef8924.png)

**Comment by yandrasindhu** [comment]
Can you please help me on this @mhamzas...

**Comment by mhamzas** [comment]
I need debug log to help you out.
Open a Browser's console log and paste here the logs. Plus, Salesforce Dev log will also be needed.

May be your user's profile doesn't have access to ContentVersion Object permissions.

**Comment by yandrasindhu** [comment]
![image](https://user-images.githubusercontent.com/39753077/78781209-74962c00-79bd-11ea-9831-b80995769b56.png)

**Comment by yandrasindhu** [comment]
@mhamzas... console is ok??

**Comment by mhamzas** [comment]
Actually I need Dev Console log.
BTW, looks like the user doesn't have access to ContentVersion and other related object WRITE permission.

**Comment by rebello1996** [comment]
The component works fine while using on desktop. But on Android Salesforce one app it is failing to record Signature. Can see only multiple dots(only the first touch point on UI). Could you provide any help here ? @mhamzas

**Comment by mhamzas** [comment]
> The component works fine while using on desktop. But on Android Salesforce one app it is failing to record Signature. Can see only multiple dots(only the first touch point on UI). Could you provide any help here ? @mhamzas

TBH, I've never tested this on Mobile App. A screenshot would be helpful though.
